/* Body file for function MemoryAccess
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "memoryaccess.h"
#include <string.h>

#include "flashd.h"
#include "flash.h"
#include "efc.h"

#define EFC_WAIT_STATE 6

static FlashAccess flash_access;

void memoryaccess_startup(void)
{
}

void memoryaccess_PI_init(asn1SccMemoryAccess_Result *OUT_result)
{
    Efc* efc = NULL;
#if defined(N7S_TARGET_SAMV71Q21)
    efc = ((Efc*)0x400E0C00U);
#elif defined(N7S_TARGET_SAMRH71F20)
    efc = ((Efc*)0x40004000U);
#else
#error "Unknown platform"
#endif

    uint32_t result = EFC_PerformCommand(efc, EFC_FCMD_GETD, 0, 0);
    uint32_t flash_description = EFC_GetResult(efc);
    uint32_t flash_size = EFC_GetResult(efc);
    uint32_t flash_page_size = EFC_GetResult(efc);
    uint32_t flash_plane_count = EFC_GetResult(efc);
    uint32_t flash_plane_size = 0;
    for(uint32_t i = 0; i < flash_plane_count; ++i) {
        flash_plane_size = EFC_GetResult(efc);
    }
    uint32_t flash_lock_bits = EFC_GetResult(efc);
    uint32_t flash_lock_region = EFC_GetResult(efc);

    EFC_SetWaitState(efc, EFC_WAIT_STATE);

    flash_access.efc = efc;

#if defined(N7S_TARGET_SAMV71Q21)
    flash_access.address = 0x00400000u;
#elif defined(N7S_TARGET_SAMRH71F20)
   flash_access.address = 0x10000000u;
#else
#error "Unknown platform"
#endif
    flash_access.size = flash_size;
    flash_access.page_size = flash_page_size;
    flash_access.page_count = flash_access.size / flash_access.page_size;
    flash_access.lock_bits = flash_lock_bits;
    flash_access.lock_region_size = flash_lock_region;
    FLASHD_Initialize(&flash_access, 0, 0);
    *OUT_result = true;
}

void memoryaccess_PI_memory_read
      (const asn1SccMemoryAccess_Address *IN_address, const asn1SccMemoryAccess_Size *IN_size,
       asn1SccMemoryAccess_Data *OUT_memdata, asn1SccMemoryAccess_Result *OUT_result)

{
    void* address = (void*)(*IN_address);
    memcpy(OUT_memdata->arr, address, *IN_size);
    OUT_memdata->nCount = *IN_size;
    *OUT_result = true;
}

void memoryaccess_PI_memory_write
      (const asn1SccMemoryAccess_Address *IN_address,
       const asn1SccMemoryAccess_Data *IN_memdata, asn1SccMemoryAccess_Result *OUT_result)

{
    if(*IN_address >= flash_access.address && *IN_address < flash_access.address + flash_access.size) {
        uint32_t result = FLASHD_Write(&flash_access, *IN_address, IN_memdata->arr, IN_memdata->nCount);
        if(result != 0) {
            *OUT_result = false;
        } else {
            *OUT_result = true;
        }
    } else {
        void* address = (void*)(*IN_address);
        memcpy(address, IN_memdata->arr, IN_memdata->nCount);
        *OUT_result = true;
    }
}

void memoryaccess_PI_memory_erase(const asn1SccMemoryAccess_Address *IN_address, const asn1SccMemoryAccess_Size *IN_size, asn1SccMemoryAccess_Result *OUT_result)
{
    if(*IN_address >= flash_access.address && *IN_address < flash_access.address + flash_access.size) {
        uint32_t page_address = (*IN_address / flash_access.page_size) * flash_access.page_size;
        uint32_t page_offset = *IN_address % flash_access.page_size;
        uint32_t pages_count = (page_offset + *IN_size) / flash_access.page_size;
        uint32_t result = FLASHD_ErasePages(&flash_access, page_address, pages_count);
        if(result != 0) {
            *OUT_result = false;
        } else {
            *OUT_result = true;
        }
    } else {
        *OUT_result = false;
    }
}

