/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <string.h>

typedef enum
{
    ISTATE_START,
    ISTATE_MEM_INITIALIZED,
    ISTATE_MEM_PROXY_INITIALIZED,
    ISTATE_FILESYSTEM_INITIALIZED,
    ISTATE_FILE_A_CREATED,
    ISTATE_FILE_A_WRITTEN,
    ISTATE_FILE_A_CHECKED,
} InternalState;

static InternalState internal_state;
static bool fail = false;

static const asn1SccMEMORY_BLOCK_INDEX block_size = 8192; // 512 * 16
static const asn1SccT_UInt32 read_size = 16;
static const asn1SccT_UInt32 prog_size = 16;
static const asn1SccT_UInt32 block_count = 256; // 2097152 / 8192
static const asn1SccT_UInt32 block_cycles = 500;
static const asn1SccT_UInt32 cache_size = 16;
static const asn1SccT_UInt32 lookahead_size = 16;

static void dbg()
{
    asm volatile ("nop");
}

static void init_memory_access()
{
    asn1SccMemoryAccess_Result result;
    testfunction_RI_MemoryAccess_init(&result);
    if(result) {
        internal_state = ISTATE_MEM_INITIALIZED;
    }
    else {
        fail = true;
        dbg();
    }
}

static void init_memory_access_proxy()
{
    asn1SccMEMORY_BLOCK_INDEX block_size;
    testfunction_RI_MemoryAccessProxy_init(&block_size);
    internal_state = ISTATE_MEM_PROXY_INITIALIZED;
}

static void init_filesystem_access()
{
    asn1SccT_Boolean result = false;
    testfunction_RI_init(&read_size, &prog_size, &block_size, &block_count, &block_cycles, &cache_size, &lookahead_size, &result);
    if(result) {
        internal_state = ISTATE_FILESYSTEM_INITIALIZED;
    } else {
        fail = true;
        dbg();
    }
}

static void create_file_a()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "a.txt");
    asn1SccLITTLE_FS_MAXIMUM_SIZE maximum_size = 0;
    asn1SccLITTLE_FS_ADDITIONAL_FILE_ATTRIBUTE file_attr;
    file_attr.field_data.nCount = 1;
    file_attr.field_data.arr[0] = 0xab;
    asn1SccLITTLE_FS_BOOLEAN result;

    testfunction_RI_file_handling_create_file(&file_path, &maximum_size,
                                              &file_attr, &result);

    if (result) {
        internal_state = ISTATE_FILE_A_CREATED;
    } else {
        fail = true;
        dbg();
    }
}

static void write_file_a()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "a.txt");
    asn1SccLITTLE_FS_MEMORY_OFFSET memory_offset = 0;
    asn1SccLITTLE_FS_MEMORY_DATA memory_data;
    memory_data.field_data.nCount = 4;
    memory_data.field_data.arr[0] = 'M';
    memory_data.field_data.arr[1] = 'O';
    memory_data.field_data.arr[2] = 'O';
    memory_data.field_data.arr[3] = 'N';

    asn1SccLITTLE_FS_BOOLEAN result;

    testfunction_RI_write_to_file(&file_path, &memory_offset,
                                  &memory_data, &result);

    if (result) {
        internal_state = ISTATE_FILE_A_WRITTEN;
    } else {
        fail = true;
        dbg();
    }
}

static void read_file_a()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "a.txt");
    asn1SccLITTLE_FS_MEMORY_OFFSET memory_offset = 0;
    asn1SccLITTLE_FS_MEMORY_OFFSET memory_size = 4;
    asn1SccLITTLE_FS_MEMORY_DATA out_memory_data;
    asn1SccLITTLE_FS_BOOLEAN result;

    testfunction_RI_read_file(&file_path, &memory_offset,
                             &memory_size, &out_memory_data,
                             &result);

    if (!result || !(out_memory_data.field_data.nCount == 4 &&
                     out_memory_data.field_data.arr[0] == 'M' &&
                     out_memory_data.field_data.arr[1] == 'O' &&
                    out_memory_data.field_data.arr[2] == 'O' &&
                    out_memory_data.field_data.arr[3] == 'N')) {
        internal_state = ISTATE_FILE_A_CHECKED;
    } else {
        fail = true;
        dbg();
    }
}

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
    if(fail) {
        return;
    }
    switch(internal_state) {
    case ISTATE_START:
        init_memory_access();
        break;
    case ISTATE_MEM_INITIALIZED:
        init_memory_access_proxy();
        break;
    case ISTATE_MEM_PROXY_INITIALIZED:
        init_filesystem_access();
        break;
    case ISTATE_FILESYSTEM_INITIALIZED:
        create_file_a();
        break;
    case ISTATE_FILE_A_CREATED:
        write_file_a();
        break;
    case ISTATE_FILE_A_WRITTEN:
        read_file_a();
        break;
    case ISTATE_FILE_A_CHECKED:
        break;
    }
}

