/* Body file for function data_pool
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "data_pool.h"
//#include <stdio.h>


void data_pool_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[data_pool] Startup");
}

void data_pool_PI_data_pool_read_parameter_value
      (const asn1SccMEMORY_BLOCK_INDEX *IN_parameter_id,
       const asn1SccMEMORY_BLOCK_INDEX *IN_parameter_value,
       const asn1SccMEMORY_BLOCK_INDEX *IN_parameter_bit_length,
       const asn1SccMEMORY_BLOCK_INDEX *IN_result)

{
   // Write your code here
}


