/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <stdint.h>

typedef enum {
    DO_INIT,
    DO_ERASE_A,
    DO_WRITE_A,
    DO_READ_A,
    DO_ERASE_B,
    DO_WRITE_B,
    DO_READ_B,
    FINISHED,
} TestState;

static TestState currentState = DO_INIT;
static bool fail = false;
static bool success = false;

#if defined(N7S_TARGET_SAMV71Q21)
/* SAMV71 */
static const asn1SccMemoryAccess_Address flash_address = 0x00400000u;
static uint32_t* inflashptr = (uint32_t*)(flash_address + 512 + 508); // last 4 bytes of second page
#elif defined(N7S_TARGET_SAMRH71F20)
/* SAMRH71 */
static const asn1SccMemoryAccess_Address flash_address = 0x10000000u;
static uint32_t* inflashptr = (uint32_t*)(flash_address + 256 + 252); // last 4 bytes of second page
#else
#error "Unknown platform"
static const asn1SccMemoryAccess_Address flash_address = 0x0u;
static uint32_t* inflashptr = 0x0u;
#endif

void testfunction_startup(void)
{
}

static void after_init()
{
    asm volatile("nop");
}

static void after_erase()
{
    asm volatile("nop");
}

static void after_read()
{
    asm volatile("nop");
}

static void after_write()
{
    asm volatile("nop");
}


void testfunction_PI_trigger(void)
{
    if(currentState == DO_INIT) {
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_init(&result);
        if(result == 0) {
            fail = true;
        }
        currentState = DO_ERASE_A;
        after_init();
    }
    if(currentState == DO_ERASE_A && !fail) {
        asn1SccMemoryAccess_Address address = (asn1SccMemoryAccess_Address)flash_address;
        asn1SccMemoryAccess_Size size = 8192;
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_memory_erase(&address, &size, & result);
        if(result == 0) {
            fail = true;
        }
        currentState = DO_WRITE_A;
        after_erase();
    }
    if(currentState == DO_WRITE_A && !fail)
    {
        asn1SccMemoryAccess_Data data;
        data.arr[0] = 0x01;
        data.arr[1] = 0x02;
        data.arr[2] = 0x03;
        data.arr[3] = 0x04;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_memory_write(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        currentState = DO_READ_A;
        after_write();
    }
    if(currentState == DO_READ_A && !fail)
    {
        asn1SccMemoryAccess_Data data;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Size size = 4;
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_memory_read(&addr, &size, &data, &result);
        if(result == 0) {
            fail = true;
        }
        if(data.nCount != 4)
        {
            fail = true;
        }
        if(data.arr[0] != 0x01 || data.arr[1] != 0x02 || data.arr[2] != 0x03 || data.arr[3] != 0x04) {
            fail = true;
        }
        currentState = DO_ERASE_B;
        after_read();
    }
    if(currentState == DO_ERASE_B && !fail) {
        asn1SccMemoryAccess_Address address = (asn1SccMemoryAccess_Address)flash_address;
        asn1SccMemoryAccess_Size size = 8192;
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_memory_erase(&address, &size, & result);
        if(result == 0) {
            fail = true;
        }
        currentState = DO_WRITE_B;
        after_erase();
    }
    if(currentState == DO_WRITE_B && !fail)
    {
        asn1SccMemoryAccess_Data data;
        data.arr[0] = 0xaa;
        data.arr[1] = 0xbb;
        data.arr[2] = 0xcc;
        data.arr[3] = 0xdd;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = false;
        testfunction_RI_memory_write(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        currentState = DO_READ_B;
        after_write();
    }
    if(currentState == DO_READ_B && !fail)
    {
        asn1SccMemoryAccess_Data data;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = false;
        asn1SccMemoryAccess_Size size = 4;
        testfunction_RI_memory_read(&addr, &size, &data, &result);
        if(result == 0) {
            fail = true;
        }
        if(data.arr[0] != 0xaa || data.arr[1] != 0xbb || data.arr[2] != 0xcc || data.arr[3] != 0xdd) {
            fail = true;
        }
        else {
            success = !fail;
        }
        currentState = FINISHED;
        after_read();
    }
}


