/* Body file for function FileSystemProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "filesystemproxy.h"
#include "string.h"


void filesystemproxy_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[FileSystemProxy] Startup");
}

void filesystemproxy_PI_read_object_memory
      (const asn1SccASW_MEMORY_BASE *IN_memory_base,
       const asn1SccASW_MEMORY_OFFSET *IN_offset,
       const asn1SccASW_MEMORY_OFFSET *IN_length,
       asn1SccASW_MEMORY_DATA *OUT_content,
       asn1SccASW_BOOLEAN *OUT_result)

{
    if(IN_memory_base->kind != ASW_MEMORY_BASE_little_fs_PRESENT) {
        *OUT_result = false;
    }
    asn1SccLITTLE_FS_REPOSITORY_PATH path = {.field_data = '\0' };
    strncat(path.field_data, IN_memory_base->u.little_fs.repository_path.field_data, 9);
    strncat(path.field_data, "/", 9);
    strncat(path.field_data, IN_memory_base->u.little_fs.file_name.field_data, 9);
    asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
    asn1SccLITTLE_FS_MEMORY_OFFSET length = *IN_length;
    asn1SccLITTLE_FS_MEMORY_DATA data;
    asn1SccLITTLE_FS_BOOLEAN result;
    filesystemproxy_RI_read_file(&path, &offset, &length, &data, &result);
    if(result == true) {
        memcpy(OUT_content->field_data.arr, data.field_data.arr, length);
        OUT_content->field_data.nCount = length;
        *OUT_result = true;
    } else {
        *OUT_result = false;
    }
}


void filesystemproxy_PI_write_object_memory
      (const asn1SccASW_MEMORY_BASE *IN_memory_base,
       const asn1SccASW_MEMORY_OFFSET *IN_offset,
       const asn1SccASW_MEMORY_DATA *IN_content,
       asn1SccASW_BOOLEAN *OUT_result)

{
    if(IN_memory_base->kind != ASW_MEMORY_BASE_little_fs_PRESENT) {
        *OUT_result = false;
    }
    asn1SccLITTLE_FS_REPOSITORY_PATH path = {.field_data = '\0' };
    strncat(path.field_data, IN_memory_base->u.little_fs.repository_path.field_data, 9);
    strncat(path.field_data, "/", 9);
    strncat(path.field_data, IN_memory_base->u.little_fs.file_name.field_data, 9);
    asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
    asn1SccLITTLE_FS_MEMORY_DATA data;
    memcpy(data.field_data.arr, IN_content->field_data.arr, IN_content->field_data.nCount);
    data.field_data.nCount = IN_content->field_data.nCount;
    filesystemproxy_RI_write_to_file(&path, &offset, &data, OUT_result);
}


