/* Header file for function MemoryAccess
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void memoryaccess_startup(void);

/* Provided interfaces */
void memoryaccess_PI_init( const asn1SccMemoryAccess_Address *, const asn1SccMemoryAccess_Size *, asn1SccMemoryAccess_Result * );


void memoryaccess_PI_memory_erase( const asn1SccMemoryAccess_Address *, const asn1SccMemoryAccess_Size *, asn1SccMemoryAccess_Result * );


void memoryaccess_PI_memory_read( const asn1SccMemoryAccess_Address *, asn1SccMemoryAccess_Data *, asn1SccMemoryAccess_Result * );


void memoryaccess_PI_memory_write( const asn1SccMemoryAccess_Address *, const asn1SccMemoryAccess_Data *, asn1SccMemoryAccess_Result * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
