/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <stdint.h>

static int counter = 0;
static bool fail = false;
static bool success = false;

/* SAMRH71 */
static const asn1SccMemoryAccess_Address flash_address = 0x10000000u;
static const asn1SccMemoryAccess_Size flash_size = 0x20000u;
static uint32_t* inflashptr = (uint32_t*)(flash_address + 256 + 252); // last 4 bytes of page

void testfunction_startup(void)
{
}

static void after_init()
{
    asm volatile("nop");
}

static void after_erase()
{
    asm volatile("nop");
}

static void after_read()
{
    asm volatile("nop");
}

static void after_write()
{
    asm volatile("nop");
}


void testfunction_PI_trigger(void)
{
    ++counter;
    if(counter == 2) {
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_init(&flash_address, &flash_size, &result);
        if(result == 0) {
            fail = true;
        }
        after_init();
    }
    if(counter == 3) {
        asn1SccMemoryAccess_Address address = (asn1SccMemoryAccess_Address)flash_address;
        asn1SccMemoryAccess_Size size = 8192;
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_erase(&address, &size, & result);
        if(result == 0) {
            fail = true;
        }
        after_erase();
    }
    if(counter == 5 && !fail)
    {
        asn1SccMemoryAccess_Data data;
        data.arr[0] = 0x01;
        data.arr[1] = 0x02;
        data.arr[2] = 0x03;
        data.arr[3] = 0x04;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_write(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        after_write();
    }
    if(counter == 7 && !fail)
    {
        asn1SccMemoryAccess_Data data;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_read(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        if(data.arr[0] != 0x01 || data.arr[1] != 0x02 || data.arr[2] != 0x03 || data.arr[3] != 0x04) {
            fail = true;
        }
        after_read();
    }
    if(counter == 9 && !fail) {
        asn1SccMemoryAccess_Address address = (asn1SccMemoryAccess_Address)flash_address;
        asn1SccMemoryAccess_Size size = 8192;
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_erase(&address, &size, & result);
        if(result == 0) {
            fail = true;
        }
        after_erase();
    }
    if(counter == 11 && !fail)
    {
        asn1SccMemoryAccess_Data data;
        data.arr[0] = 0xaa;
        data.arr[1] = 0xbb;
        data.arr[2] = 0xcc;
        data.arr[3] = 0xdd;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_write(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        after_write();
    }
    if(counter == 13 && !fail)
    {
        asn1SccMemoryAccess_Data data;
        asn1SccMemoryAccess_Address addr = (asn1SccMemoryAccess_Address)(inflashptr);
        asn1SccMemoryAccess_Result result = 0;
        testfunction_RI_memory_read(&addr, &data, &result);
        if(result == 0) {
            fail = true;
        }
        if(data.arr[0] != 0xaa || data.arr[1] != 0xbb || data.arr[2] != 0xcc || data.arr[3] != 0xdd) {
            fail = true;
        }
        else {
            success = !fail;
        }
        after_read();
    }
}


