/* ASN.1 System configuration file for function MemoryAccess
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_MemoryAccess_Address_NATIVE
#define __NEED_MemoryAccess_Size_NATIVE
#define __NEED_MemoryAccess_Result_NATIVE


#define __NEED_MemoryAccess_Address_NATIVE
#define __NEED_MemoryAccess_Size_NATIVE
#define __NEED_MemoryAccess_Result_NATIVE


#define __NEED_MemoryAccess_Address_NATIVE
#define __NEED_MemoryAccess_Data_NATIVE
#define __NEED_MemoryAccess_Result_NATIVE


#define __NEED_MemoryAccess_Address_NATIVE
#define __NEED_MemoryAccess_Data_NATIVE
#define __NEED_MemoryAccess_Result_NATIVE

