/* Header file for function MemoryAccess
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "memoryaccess.h"

// Function initialization - calls user startup code of all dependent functions
void init_memoryaccess(void);


/* Provided interfaces */
void memoryaccess_init
      (const char *IN_flash_address, size_t IN_flash_address_len,
       const char *IN_flash_size, size_t IN_flash_size_len,
       char *OUT_result, size_t *OUT_result_len);



void memoryaccess_memory_erase
      (const char *IN_address, size_t IN_address_len,
       const char *IN_size, size_t IN_size_len,
       char *OUT_result, size_t *OUT_result_len);



void memoryaccess_memory_read
      (const char *IN_address, size_t IN_address_len,
       char *OUT_memdata, size_t *OUT_memdata_len,
       char *OUT_result, size_t *OUT_result_len);



void memoryaccess_memory_write
      (const char *IN_address, size_t IN_address_len,
       const char *IN_memdata, size_t IN_memdata_len,
       char *OUT_result, size_t *OUT_result_len);


#ifdef __cplusplus
}
#endif

