/* Body file for function MemoryAccess
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "memoryaccess_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void memoryaccess_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned memoryaccess_initialized = 0;
void init_memoryaccess(void)
{
   if (0 == memoryaccess_initialized) {
      memoryaccess_initialized = 1;
      // Call user code startup function
      extern void memoryaccess_startup(void);
      memoryaccess_startup();
      memoryaccess_initialized = 2;
   }
}
void memoryaccess_init
      (const char *IN_flash_address, size_t IN_flash_address_len,
       const char *IN_flash_size, size_t IN_flash_size_len,
       char *OUT_result, size_t *OUT_result_len)

{
   sender_pid = memoryaccess_init_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void memoryaccess_PI_init
      (const asn1SccMemoryAccess_Address *,
       const asn1SccMemoryAccess_Size *,
       asn1SccMemoryAccess_Result *);





   // Call user code
   memoryaccess_PI_init ((asn1SccMemoryAccess_Address *)IN_flash_address, (asn1SccMemoryAccess_Size *)IN_flash_size, (asn1SccMemoryAccess_Result *)OUT_result);

}




void memoryaccess_memory_erase
      (const char *IN_address, size_t IN_address_len,
       const char *IN_size, size_t IN_size_len,
       char *OUT_result, size_t *OUT_result_len)

{
   sender_pid = memoryaccess_memory_erase_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void memoryaccess_PI_memory_erase
      (const asn1SccMemoryAccess_Address *,
       const asn1SccMemoryAccess_Size *,
       asn1SccMemoryAccess_Result *);





   // Call user code
   memoryaccess_PI_memory_erase ((asn1SccMemoryAccess_Address *)IN_address, (asn1SccMemoryAccess_Size *)IN_size, (asn1SccMemoryAccess_Result *)OUT_result);

}




void memoryaccess_memory_read
      (const char *IN_address, size_t IN_address_len,
       char *OUT_memdata, size_t *OUT_memdata_len,
       char *OUT_result, size_t *OUT_result_len)

{
   sender_pid = memoryaccess_memory_read_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void memoryaccess_PI_memory_read
      (const asn1SccMemoryAccess_Address *,
       asn1SccMemoryAccess_Data *,
       asn1SccMemoryAccess_Result *);





   // Call user code
   memoryaccess_PI_memory_read ((asn1SccMemoryAccess_Address *)IN_address, (asn1SccMemoryAccess_Data *)OUT_memdata, (asn1SccMemoryAccess_Result *)OUT_result);

}




void memoryaccess_memory_write
      (const char *IN_address, size_t IN_address_len,
       const char *IN_memdata, size_t IN_memdata_len,
       char *OUT_result, size_t *OUT_result_len)

{
   sender_pid = memoryaccess_memory_write_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void memoryaccess_PI_memory_write
      (const asn1SccMemoryAccess_Address *,
       const asn1SccMemoryAccess_Data *,
       asn1SccMemoryAccess_Result *);





   // Call user code
   memoryaccess_PI_memory_write ((asn1SccMemoryAccess_Address *)IN_address, (asn1SccMemoryAccess_Data *)IN_memdata, (asn1SccMemoryAccess_Result *)OUT_result);

}

