#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "init"
sp = ast.ApLevelContainer("init")
ast.g_apLevelContainers["init"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Address")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("flash_address", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Address"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("init", "flash_address", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("init", "flash_address", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Size")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("flash_size", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Size"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("init", "flash_size", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("init", "flash_size", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::MemoryAccess_Result")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("result", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Result"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("init", "result", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("init", "result", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = init
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["init", "C", "C", "memoryaccess", sp._fpgaConfigurations])
sp._language = "C"


# Interface "memory_erase"
sp = ast.ApLevelContainer("memory_erase")
ast.g_apLevelContainers["memory_erase"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Address")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("address", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Address"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_erase", "address", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_erase", "address", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Size")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("size", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Size"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_erase", "size", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_erase", "size", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::MemoryAccess_Result")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("result", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Result"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_erase", "result", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_erase", "result", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = memory_erase
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["memory_erase", "C", "C", "memoryaccess", sp._fpgaConfigurations])
sp._language = "C"


# Interface "memory_read"
sp = ast.ApLevelContainer("memory_read")
ast.g_apLevelContainers["memory_read"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Address")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("address", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Address"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_read", "address", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_read", "address", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::MemoryAccess_Data")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("memdata", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Data"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_read", "memdata", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_read", "memdata", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::MemoryAccess_Result")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("result", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Result"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_read", "result", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_read", "result", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = memory_read
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["memory_read", "C", "C", "memoryaccess", sp._fpgaConfigurations])
sp._language = "C"


# Interface "memory_write"
sp = ast.ApLevelContainer("memory_write")
ast.g_apLevelContainers["memory_write"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Address")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("address", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Address"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_write", "address", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_write", "address", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::MemoryAccess_Data")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("memdata", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Data"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_write", "memdata", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_write", "memdata", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::MemoryAccess_Result")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("result", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "MemoryAccess_Result"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("memory_write", "result", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("memory_write", "result", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = memory_write
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["memory_write", "C", "C", "memoryaccess", sp._fpgaConfigurations])
sp._language = "C"



