/* Body file for function MemoryAccessProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "memoryaccessproxy.h"
#include <string.h>

static asn1SccMemoryAccess_Address flash_address;
static asn1SccMEMORY_BLOCK_INDEX fs_block_size;

void memoryaccessproxy_startup(void)
{
#if defined(N7S_TARGET_SAMV71Q21)
    flash_address = 0x00400000u;
#elif defined(N7S_TARGET_SAMRH71F20)
    flash_address = 0x10000000u;
#else
#error "Unknown platform"
#endif
}

void memoryaccessproxy_PI_MemoryAccessProxy_init( const asn1SccMEMORY_BLOCK_INDEX *IN_block_size)
{
    fs_block_size = *IN_block_size;
}

void memoryaccessproxy_PI_FileSystem_memory_erase
      (const asn1SccMEMORY_BLOCK_INDEX *IN_block_index,
       asn1SccT_Int32 *OUT_return_code)
{
    asn1SccMemoryAccess_Result result = false;
    asn1SccMemoryAccess_Address address = flash_address + (*IN_block_index * fs_block_size);
    asn1SccMemoryAccess_Size size = fs_block_size;
    memoryaccessproxy_RI_memory_erase(&address, &size, &result);
    if(result == false) {
        *OUT_return_code = 1;
    } else {
        *OUT_return_code = 0;
    }
}

void memoryaccessproxy_PI_FileSystem_memory_read
      (const asn1SccMEMORY_BLOCK_INDEX *IN_block_index,
       const asn1SccMEMORY_OFFSET *IN_block_offset,
       asn1SccMEMORY_DATA *OUT_buffer,
       const asn1SccMEMORY_SIZE *IN_data_size,
       asn1SccT_Int32 *OUT_return_code)
{
    asn1SccMemoryAccess_Result result = false;
    asn1SccMemoryAccess_Address address = flash_address + (*IN_block_index * fs_block_size) + *IN_block_offset;
    asn1SccMemoryAccess_Size size = *IN_data_size;
    asn1SccMemoryAccess_Data data;
    memoryaccessproxy_RI_memory_read(&address, &size, &data, &result);
    if(result == false) {
        *OUT_return_code = 1;
    } else {
        *OUT_return_code = 0;
        memcpy(OUT_buffer->arr, data.arr, size);
        OUT_buffer->nCount = size;
    }
}

void memoryaccessproxy_PI_memory_program
      (const asn1SccMEMORY_BLOCK_INDEX *IN_block_index,
       const asn1SccMEMORY_OFFSET *IN_block_offset,
       const asn1SccMEMORY_DATA *IN_buffer,
       const asn1SccMEMORY_SIZE *IN_data_size,
       asn1SccT_Int32 *OUT_return_code)
{
    asn1SccMemoryAccess_Result result = false;
    asn1SccMemoryAccess_Address address = flash_address + (*IN_block_index * fs_block_size) + *IN_block_offset;
    asn1SccMemoryAccess_Data data;
    memcpy(data.arr, IN_buffer->arr, *IN_data_size);
    data.nCount = *IN_data_size;
    memoryaccessproxy_RI_memory_write(&address, &data, &result);
    if(result == false) {
        *OUT_return_code = 1;
    } else {
        *OUT_return_code = 0;
    }
}

void memoryaccessproxy_PI_memory_sync
      (asn1SccT_Int32 *OUT_return_code)
{
    *OUT_return_code = 0;
}


void memoryaccessproxy_PI_read_object_memory(const asn1SccASW_MEMORY_BASE *IN_memory_base,
                                             const asn1SccASW_MEMORY_OFFSET *IN_offset,
                                             const asn1SccASW_MEMORY_OFFSET *IN_length,
                                             asn1SccASW_MEMORY_DATA *OUT_content,
                                             asn1SccASW_BOOLEAN *OUT_result)
{
        if(IN_memory_base->kind != ASW_MEMORY_BASE_little_fs_PRESENT) {
            *OUT_result = false;
            return;
        }
        asn1SccLITTLE_FS_REPOSITORY_PATH path = {.field_data = '\0' };
        strncat(path.field_data, IN_memory_base->u.little_fs.repository_path.field_data, 9);
        strncat(path.field_data, "/", 9);
        strncat(path.field_data, IN_memory_base->u.little_fs.file_name.field_data, 9);
        asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
        asn1SccLITTLE_FS_MEMORY_OFFSET length = *IN_length;
        asn1SccLITTLE_FS_MEMORY_DATA data;
        asn1SccLITTLE_FS_BOOLEAN result;
        memoryaccessproxy_RI_read_file(&path, &offset, &length, &data, &result);
        if(result == true) {
            memcpy(OUT_content->field_data.arr, data.field_data.arr, length);
            OUT_content->field_data.nCount = length;
            *OUT_result = true;
        } else {
            *OUT_result = false;
        }
}


void memoryaccessproxy_PI_read_raw_memory(const asn1SccASW_MEMORY_IDENTIFIER *IN_memory_identifier,
                                          const asn1SccASW_MEMORY_OFFSET *IN_offset,
                                          const asn1SccASW_MEMORY_OFFSET *IN_length,
                                          asn1SccASW_MEMORY_DATA *OUT_content,
                                          asn1SccASW_BOOLEAN *OUT_result)
{
    if(*IN_memory_identifier != asn1SccASW_MEMORY_IDENTIFIER_ram_memory) {
        *OUT_result = false;
        return;
    }

    asn1SccMemoryAccess_Address address = *IN_offset;
    asn1SccMemoryAccess_Size size = *IN_length;
    asn1SccMemoryAccess_Data data;
    asn1SccMemoryAccess_Result result = false;

    memoryaccessproxy_RI_memory_read(&address, &size, &data, &result);
    if(!result) {
        *OUT_result = false;
        return;
    }
    memcpy(OUT_content->field_data.arr, data.arr, data.nCount);
    OUT_content->field_data.nCount = data.nCount;
    *OUT_result = true;
}


void memoryaccessproxy_PI_write_object_memory(const asn1SccASW_MEMORY_BASE *IN_memory_base,
                                              const asn1SccASW_MEMORY_OFFSET *IN_offset,
                                              const asn1SccASW_MEMORY_DATA *IN_content,
                                              asn1SccASW_BOOLEAN *OUT_result)
{
    if(IN_memory_base->kind != ASW_MEMORY_BASE_little_fs_PRESENT) {
        *OUT_result = false;
        return;
    }
    asn1SccLITTLE_FS_REPOSITORY_PATH path = {.field_data = '\0' };
    strncat(path.field_data, IN_memory_base->u.little_fs.repository_path.field_data, 9);
    strncat(path.field_data, "/", 9);
    strncat(path.field_data, IN_memory_base->u.little_fs.file_name.field_data, 9);
    asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
    asn1SccLITTLE_FS_MEMORY_DATA data;
    memcpy(data.field_data.arr, IN_content->field_data.arr, IN_content->field_data.nCount);
    data.field_data.nCount = IN_content->field_data.nCount;
    memoryaccessproxy_RI_write_to_file(&path, &offset, &data, OUT_result);
}


void memoryaccessproxy_PI_write_raw_memory(const asn1SccASW_MEMORY_IDENTIFIER *IN_memory_identifier,
                                           const asn1SccASW_MEMORY_OFFSET *IN_offset,
                                           const asn1SccASW_MEMORY_DATA *IN_content,
                                           asn1SccASW_BOOLEAN *OUT_result)
{
    if(*IN_memory_identifier != asn1SccASW_MEMORY_IDENTIFIER_ram_memory) {
        *OUT_result = false;
        return;
    }

    asn1SccMemoryAccess_Address address = *IN_offset;
    asn1SccMemoryAccess_Data data;
    memcpy(data.arr, IN_content->field_data.arr, IN_content->field_data.nCount);
    data.nCount = IN_content->field_data.nCount;
    asn1SccMemoryAccess_Result result = false;

    memoryaccessproxy_RI_memory_write(&address, &data, &result);
    *OUT_result = result;
}



